// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Affiliation Entity affiliation/allegiance classification
//
// swagger:model Affiliation
type Affiliation string

func NewAffiliation(value Affiliation) *Affiliation {
	return &value
}

// Pointer returns a pointer to a freshly-allocated Affiliation.
func (m Affiliation) Pointer() *Affiliation {
	return &m
}

const (

	// AffiliationFRIENDLY captures enum value "FRIENDLY"
	AffiliationFRIENDLY Affiliation = "FRIENDLY"

	// AffiliationHOSTILE captures enum value "HOSTILE"
	AffiliationHOSTILE Affiliation = "HOSTILE"

	// AffiliationNEUTRAL captures enum value "NEUTRAL"
	AffiliationNEUTRAL Affiliation = "NEUTRAL"

	// AffiliationUNKNOWN captures enum value "UNKNOWN"
	AffiliationUNKNOWN Affiliation = "UNKNOWN"

	// AffiliationPENDING captures enum value "PENDING"
	AffiliationPENDING Affiliation = "PENDING"

	// AffiliationASSUMEDFRIEND captures enum value "ASSUMED_FRIEND"
	AffiliationASSUMEDFRIEND Affiliation = "ASSUMED_FRIEND"

	// AffiliationSUSPECT captures enum value "SUSPECT"
	AffiliationSUSPECT Affiliation = "SUSPECT"
)

// for schema
var affiliationEnum []interface{}

func init() {
	var res []Affiliation
	if err := json.Unmarshal([]byte(`["FRIENDLY","HOSTILE","NEUTRAL","UNKNOWN","PENDING","ASSUMED_FRIEND","SUSPECT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		affiliationEnum = append(affiliationEnum, v)
	}
}

func (m Affiliation) validateAffiliationEnum(path, location string, value Affiliation) error {
	if err := validate.EnumCase(path, location, value, affiliationEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this affiliation
func (m Affiliation) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAffiliationEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this affiliation based on context it is used
func (m Affiliation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
