package models

// KeycloakRegisterRequest represents a request to register a user using a Keycloak ID token.
// @name KeycloakRegisterRequest
type KeycloakRegisterRequest struct {
	// The user's first name.
	FirstName string `json:"first_name" binding:"required" example:"Jane" minlength:"1"`
	// The user's last name.
	LastName string `json:"last_name" binding:"required" example:"Doe" minlength:"1"`
	// The JWT ID token provided by Keycloak upon successful user authentication.
	IDToken string `json:"id_token" binding:"required" example:"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJFRXB2UXpvSzVhczNlZVE2RVR1aW1QTkpnYzQyWEpmRVgwbDZEbHFzdUZnIn0.eyJleHAiOjE3NDU0NTQyMzcsImlhdCI6MTc0NTQ1MzkzNywiYXV0aF90aW1lIjoxNzQ1NDUyNzUxLCJqdGkiOiI5ZjBhMWVjZS04NGUxLTRmNWQtYTllZC1mOTA5ZDAwNmUwMDQiLCJpc3MiOiJodHRwczovL2F1dGgubGVnaW9uLXN0YWdpbmcuY29tL3JlYWxtcy9sZWdpb24iLCJhdWQiOiJvcmlvbi1kZW1vIiwic3ViIjoiYWRhMjc5MjgtMDcwNy00YTcwLWE4NzUtZDkyYWU1ODBlNGIxIiwidHlwIjoiSUQiLCJhenAiOiJvcmlvbi1kZW1vIiwibm9uY2UiOiI2YzIwOTRjZS1mNzY3LTRlYjMtYTQzMS1lOWQ5MzEzNTRiZmYiLCJzaWQiOiI4NmMyZWIzZi1mZTUyLTQyODgtYjc1MC00YTk0YmUyNjYwMWYiLCJhdF9oYXNoIjoiRFByeVVWVWVaWHFibDVwaW4yanFZZyIsImFjciI6IjAiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJFbWlsIFRlc3QiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJlbWlsK3Rlc3RAcGljb2dyaWQuY29tIiwiZ2l2ZW5fbmFtZSI6IkVtaWwiLCJmYW1pbHlfbmFtZSI6IlRlc3QiLCJlbWFpbCI6ImVtaWwrdGVzdEBwaWNvZ3JpZC5jb20ifQ.xw2184w2y_R6ukud1fXOXk9S5H8auzV6p-Y1fCifWfJQS11Oa_3_nMT0YZSO7BsriKL6W4rMwYXBiWYA1qZ0SSIJ896zZ2DU1-FZLVuU5Ar1y3laZdrBtSb6tNrmDvPxJvakpRrg8SUt4-eKDi4CUCHHfd7F7pzSOVkFRhYRSZQ6c-0OxrLtrhBWxLl8pSBay8QEtJHxT7zZk2RemTRNV3c1-difh53iIDgokfl5pJhSxpftxkxY_ERhQ_z8bWHBo-pR_EinUhl-mSdzhen4w7-QN7iRvZevLKF9Ot7ek2r4Ow8MrvglTXasDXfn_wM-eur8-zvw1YtbHgFQNN9Qfw"`
}
