// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrorsDetail errors detail
//
// swagger:model errors.Detail
type ErrorsDetail struct {

	// The field that caused the error
	// example: email
	Field string `json:"field,omitempty"`

	// The specific issue with the field
	// example: Invalid email format
	Issue string `json:"issue,omitempty"`
}

// Validate validates this errors detail
func (m *ErrorsDetail) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this errors detail based on context it is used
func (m *ErrorsDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrorsDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorsDetail) UnmarshalBinary(b []byte) error {
	var res ErrorsDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
