// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GeomPoint geom point
//
// swagger:model GeomPoint
type GeomPoint struct {

	// ECEF coordinates [x, y, z]
	// Example: [4517590.878,832293.16,4524856.575]
	// Required: true
	// Max Items: 3
	// Min Items: 3
	Coordinates []float64 `json:"coordinates"`

	// type
	// Example: Point
	// Required: true
	// Enum: ["Point"]
	Type *string `json:"type"`
}

// Validate validates this geom point
func (m *GeomPoint) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCoordinates(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GeomPoint) validateCoordinates(formats strfmt.Registry) error {

	if err := validate.Required("coordinates", "body", m.Coordinates); err != nil {
		return err
	}

	iCoordinatesSize := int64(len(m.Coordinates))

	if err := validate.MinItems("coordinates", "body", iCoordinatesSize, 3); err != nil {
		return err
	}

	if err := validate.MaxItems("coordinates", "body", iCoordinatesSize, 3); err != nil {
		return err
	}

	return nil
}

var geomPointTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Point"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		geomPointTypeTypePropEnum = append(geomPointTypeTypePropEnum, v)
	}
}

const (

	// GeomPointTypePoint captures enum value "Point"
	GeomPointTypePoint string = "Point"
)

// prop value enum
func (m *GeomPoint) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, geomPointTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GeomPoint) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this geom point based on context it is used
func (m *GeomPoint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GeomPoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GeomPoint) UnmarshalBinary(b []byte) error {
	var res GeomPoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
