// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServiceIngestMessageRequest service ingest message request
//
// swagger:model ServiceIngestMessageRequest
type ServiceIngestMessageRequest struct {

	// data
	// Required: true
	Data interface{} `json:"data"`

	// feed id
	// Required: true
	// Format: uuid
	FeedID *strfmt.UUID `json:"feed_id"`

	// timestamp
	// Format: date-time
	Timestamp strfmt.DateTime `json:"timestamp,omitempty"`
}

// Validate validates this service ingest message request
func (m *ServiceIngestMessageRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFeedID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceIngestMessageRequest) validateData(formats strfmt.Registry) error {

	if m.Data == nil {
		return errors.Required("data", "body", nil)
	}

	return nil
}

func (m *ServiceIngestMessageRequest) validateFeedID(formats strfmt.Registry) error {

	if err := validate.Required("feed_id", "body", m.FeedID); err != nil {
		return err
	}

	if err := validate.FormatOf("feed_id", "body", "uuid", m.FeedID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ServiceIngestMessageRequest) validateTimestamp(formats strfmt.Registry) error {
	if swag.IsZero(m.Timestamp) { // not required
		return nil
	}

	if err := validate.FormatOf("timestamp", "body", "date-time", m.Timestamp.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this service ingest message request based on context it is used
func (m *ServiceIngestMessageRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceIngestMessageRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceIngestMessageRequest) UnmarshalBinary(b []byte) error {
	var res ServiceIngestMessageRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
