name: Unit Tests

on:
  # workflow_call makes it reusable
   workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Unit Tests
        run: make unit-test

      - name: Upload Test Results
        if: always() # Always run this step to upload results, even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: unit-results.json

      - name: Post Test Summary
        if: always() # Always run this step to post summary
        uses: robherley/go-test-action@v0
        with:
          fromJSONFile: unit-results.json
